name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js v16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Clone `waallet-extension`
        uses: actions/checkout@v4
        with:
          repository: "pilagod/waallet-extension"
          path: "waallet-extension"

      - name: Set up `waallet-extension`
        working-directory: "waallet-extension"
        run: npm ci

      - name: Run linter
        working-directory: "waallet-extension"
        run: npm run lint

      - name: Clone `waallet-contract`
        uses: actions/checkout@v4
        with:
          repository: "pilagod/waallet-contract"
          path: "waallet-contract"
          submodules: recursive

      - name: Spin up testnet
        working-directory: "waallet-contract"
        run: docker compose -f ./docker/testnet/docker-compose-node.yml up --build -d

      - name: Wait for testnet initialized
        run: sleep 10s
        shell: bash

      - name: Set up testnet
        working-directory: "waallet-contract"
        run: docker compose -f ./docker/testnet/docker-compose-node-setup.yml up --build

      - name: Run tests
        working-directory: "waallet-extension"
        run: npm run test
